### ISSUE TITLE
qt5-static Core component doesn’t work on its own

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#4081]
using `Widgets` instead of `Core` links successfully
```
project(qt5corelink)
cmake_minimum_required(VERSION 3.0)

find_package(Qt5 REQUIRED COMPONENTS Core)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} Qt5::Core)
```
```
#include <QDebug>
#include <QtGlobal>

int main() {
    qDebug() << qVersion();
}
```
```
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x20a): undefined reference to `pcre2_match_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x27a): undefined reference to `pcre2_jit_stack_create_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x46d): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x56d): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5bc): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5cd): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5f2): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x60e): undefined reference to `pcre2_config_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x719): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x7da): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x90e): undefined reference to `pcre2_jit_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0xa22): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0xc91): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0xd75): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0xee4): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x1063): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x114c): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x120d): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x132c): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x13ed): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x1567): undefined reference to `pcre2_get_error_message_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x16bc): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x177d): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x189c): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x195d): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x1a59): undefined reference to `pcre2_jit_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x1b2a): undefined reference to `pcre2_jit_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x1ee6): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x20b9): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x239e): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x247e): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2567): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2637): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x272b): undefined reference to `pcre2_substring_number_from_name_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x28fa): more undefined references to `pcre2_substring_number_from_name_16' follow
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2c3e): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2d3e): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2ed5): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2ffe): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x33ec): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x3509): more undefined references to `pcre2_code_free_16' follow
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4929): undefined reference to `pcre2_match_context_create_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4940): undefined reference to `pcre2_jit_stack_assign_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x494b): undefined reference to `pcre2_match_data_create_from_pattern_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4a09): undefined reference to `pcre2_get_ovector_pointer_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4a76): undefined reference to `pcre2_match_data_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4a80): undefined reference to `pcre2_match_context_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4ac2): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4d80): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4e39): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x4ef9): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x506c): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5382): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5523): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x55e6): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5797): undefined reference to `pcre2_match_context_create_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x57ac): undefined reference to `pcre2_jit_stack_assign_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x57b7): undefined reference to `pcre2_match_data_create_from_pattern_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5867): undefined reference to `pcre2_get_ovector_pointer_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x58d7): undefined reference to `pcre2_match_data_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x58df): undefined reference to `pcre2_match_context_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5912): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5b22): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5bdc): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5ca2): undefined reference to `pcre2_compile_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5e90): undefined reference to `pcre2_match_context_create_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5eac): undefined reference to `pcre2_jit_stack_assign_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5ebc): undefined reference to `pcre2_match_data_create_from_pattern_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5f7a): undefined reference to `pcre2_get_ovector_pointer_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5fe9): undefined reference to `pcre2_match_data_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x5ff3): undefined reference to `pcre2_match_context_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6026): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x62a0): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6477): undefined reference to `pcre2_match_context_create_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x648c): undefined reference to `pcre2_jit_stack_assign_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6497): undefined reference to `pcre2_match_data_create_from_pattern_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6562): undefined reference to `pcre2_get_ovector_pointer_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x65d8): undefined reference to `pcre2_match_data_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x65e0): undefined reference to `pcre2_match_context_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6622): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6880): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6959): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x696f): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6985): undefined reference to `pcre2_pattern_info_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x6fbb): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x722a): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x72cb): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x757a): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x76a5): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text+0x2e3): undefined reference to `pcre2_match_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN14QThreadStorageIP20QPcreJitStackPointerE10deleteDataEPv[_ZN14QThreadStorageIP20QPcreJitStackPointerE10deleteDataEPv]+0x16): undefined reference to `pcre2_jit_stack_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN28QExplicitlySharedDataPointerI25QRegularExpressionPrivateED1Ev[_ZN28QExplicitlySharedDataPointerI25QRegularExpressionPrivateED1Ev]+0x31): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN18QSharedDataPointerI30QRegularExpressionMatchPrivateED1Ev[_ZN18QSharedDataPointerI30QRegularExpressionMatchPrivateED1Ev]+0xa6): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE6detachEv[_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE6detachEv]+0xc0): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE6detachEv[_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE6detachEv]+0x1d1): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN18QSharedDataPointerI30QRegularExpressionMatchPrivateE13detach_helperEv[_ZN18QSharedDataPointerI30QRegularExpressionMatchPrivateE13detach_helperEv]+0x135): undefined reference to `pcre2_code_free_16'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qregularexpression.o):qregularexpression.cpp:(.text$_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE13detach_helperEv[_ZN18QSharedDataPointerI38QRegularExpressionMatchIteratorPrivateE13detach_helperEv]+0xa5): more undefined references to `pcre2_code_free_16' follow
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0xc7d): undefined reference to `__imp_timeSetEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0xd24): undefined reference to `__imp_timeKillEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0xfa2): undefined reference to `__imp_timeSetEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0x1b06): undefined reference to `__imp_timeKillEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0x1df7): undefined reference to `__imp_timeKillEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0x222e): undefined reference to `__imp_timeSetEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qeventdispatcher_win.o):qeventdispatcher_win.cpp:(.text+0x2dd7): undefined reference to `__imp_timeKillEvent'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qcoreapplication_win.o):qcoreapplication_win.cpp:(.text+0x2e1): undefined reference to `GetFileVersionInfoSizeW'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qcoreapplication_win.o):qcoreapplication_win.cpp:(.text+0x32d): undefined reference to `GetFileVersionInfoW'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qcoreapplication_win.o):qcoreapplication_win.cpp:(.text+0x427): undefined reference to `VerQueryValueW'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qfilesystemengine_win.o):qfilesystemengine_win.cpp:(.text+0x3092): undefined reference to `__imp_GetUserProfileDirectoryW'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qfilesystemengine_win.o):qfilesystemengine_win.cpp:(.text+0x4089): undefined reference to `NetApiBufferFree'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qfilesystemengine_win.o):qfilesystemengine_win.cpp:(.text+0x40cb): undefined reference to `NetShareEnum'
D:/msys64/mingw64/qt5-static/lib/libQt5Core.a(qfilesystemengine_win.o):qfilesystemengine_win.cpp:(.text+0x419c): undefined reference to `NetApiBufferFree'
```

**Comment by Alexpux** [comment]
@Optiligence  ````libqtpcre2.a```` presense in Qt5Core.prl so it maybe issue in qt5 cmake patches, but I'm not a mainterner of then and dont have time to solve it
