### PR TITLE
clang: update to 4.0.0

### PR DESCRIPTION
**Pull request by mati865**
Do not merge yet, cc @martell .

`libc++`, `libc++abi`, `libunwind`, `lld` are disabled because they are broken too much.
Other packages should be working (Clang bugs reported here aren't fixed).
Additionally LLVM is now linked dynamically because otherwise `llvm-config --link-shared` breaks.

### CODE REVIEW

**Comment by hcorion** [comment]
Can you test if rust still works? I'm pretty sure it depends on libunwind. I think it may build it's own version, but I'm not 100% sure.

**Comment by mati865** [comment]
As far as I know LLVM libunwind was used only for libc++ and rust provides own libunwind using `gcc_eh` for mingw build.

BTW I'm preparing rust 1.16 release with rustbuild system.

**Comment by hcorion** [comment]
Awesome! It would also be cool if you fixed bug #2143 in your 1.16 PR by adding libssh2 as a dependency.

**Comment by mati865** [comment]
My plan is to move cargo to own package as well (like all Linux distributions do).
Of course fix will be included.

**Comment by mati865** [comment]
Force pushed to add new patch: `0007-add-pthread-as-system-lib-for-mingw.patch` and restore old `0502-hack-to-use-64-bit-time-for-mingw.patch`.

**Comment by mati865** [comment]
@Alexpux I think it's ok to merge, both libc++ and lld never worked in MSYS2 and now they don't build.

**Comment by Alexpux** [comment]
I dont want to merge without libc++ and lld because we already have this packages in repository. If I'm upload new packages without those parts then we get issues with updating llvm packages on user systems who install libc++ and lld. And also I will need remove not builder parts from pacman databases

**Comment by martell** [comment]
Hey @mati865,
Good start here.

Does `HasFloat128 = true;` fix the issue with the large revert we had to do previously?
Also could you share your errors when building lld libunwind 4.0 etc?
I can have a look.

Best,
Martell

**Comment by mati865** [comment]
@martell, Hey.
`HasFloat128 = true;` tricks libstc++ to think Clang supports _float128 but doesn't expose `__FLOAT128__` define. Trying to use _float128 fill cause compilation error which is way better than segfault from running app.
Simple and brilliant, isn't it?
Downside is [failing test](https://gist.github.com/mati865/3a350709f853e4a8cb1fc40980a4f5b0) `Sema/128bitfloat.cpp` but I think we can live without it 😄.
Also I wanted to post my findings on the [LLVM bugzilla](https://bugs.llvm.org//show_bug.cgi?id=30685) but registration is "temporary" disabled...

LLD patches didn't apply and there was some code refactoring so I just disabled it as it is even less useful than before. Although it build fine so I'll update PR soon.

libc++ has seen big changes but after spending more hours than I wanted it is building without libunwind which is WIP. I think I'll get it ready tomorrow.

**Comment by mati865** [comment]
Good news, everything builds now.

Some optimistic notes:

- LLD was already useless before and now without patches it's even more useless.
- libc++ was totally broken and now is even more broken (including <iostream> will cause error `D:\msys64\mingw32\include\c++\v1\__bsd_locale_fallbacks.h:121:17: error: use of undeclared identifier 'vasprintf'; did you mean 'vsprintf'?`)

In summary 2 broken features are even more broken.

**Comment by martell** [comment]
LLD works just not with anything built with binutils :)

libc++ HEAD now almost passes fully for the MSVC target as standalone.
Adding MINGW support on top of that work is next on my list of tasks.

`vasprintf` is an actual function, you need to build with `_GNU_SOURCE` defined to 1 for it to work.

**Comment by Alexpux** [comment]
Great @martell !!!

**Comment by mati865** [comment]
@martell so it is broken for us 😶

**Comment by martell** [comment]
If the mingw-w64-crt is built with llvm-dlltool then it can be used for us.
LLD should work for every other target though which is useful also.
I think the next major llvm release will have everything we need.

@mati865 How well is lldb working btw?

**Comment by martell** [comment]
@mati865 This should be useful
http://clang-developers.42468.n3.nabble.com/Re-Newlib-v2-5-0-and-LibC-locale-support-BROKEN-td4054882.html

**Comment by mati865** [comment]
@martell Now when I'm back home from college I cannot believe I missed that `_GNU_SOURCE`.
I guess we could define it in `${MINGW_PREFIX}/include/c++/v1__config`?

I tested LLDB with WSL (also called Bash on Ubuntu on Windows) when I updated LLVM/Clang to 3.9.0. It connected and worked fine as remote.
For pure Windows usage it is very limited as `lldb-server` uses POSIX API, I enabled it in CMake back at 3.9.0 and when it failed due to missing POSIX functions I disabled it.
So we have client only which can possibly work with https://github.com/facebook/ds2 but I haven't tested it.

Using libc++ now fails with impressive 1347 broken [1] references: https://gist.github.com/mati865/cb6daee33faafe06b877b562e705c3bf
Probably the best way (not easiest) to solve it would be to fix `-nodefaultlibs` and specify required libs. Also https://github.com/Alexpux/MINGW-packages/pull/2294/files#diff-ac7dd18141827df6a35a303e84901615L181 could need to be readded as `-lc++abi` is missing in linker args.

Currently at MINGW-packages we have 2 rather serious (#1677, #1834) and another 2 important (#1678, #2247) issues open for Clang and it would be great to have them fixed but I had to gave up.

[1] There is a word that describes it more accurately but let's avoid it in public.

**Comment by revelator** [comment]
Small whoops, seems libunwind from clang breaks building glog with a multiple definition error. This might also cause other sources to fail because it includes the same symbols as libgcc which is allways linked in.
So if some source says hey i want to use libunwind with gcc it will break. You can offcourse get around that by adding a -Wl,--allow-multiple-definition to flags but it will propagate down to every source linking to that library afterwards.
